use tfmttools_core::action::Action;
use tfmttools_core::error::TFMTResult;
use tracing::trace;

use crate::fs::{FsHandler, MoveFileResult};

pub struct ActionHandler<'a> {
    fs_handler: &'a FsHandler,
    always_copy: bool,
}

impl<'a> ActionHandler<'a> {
    pub fn new(fs_handler: &'a FsHandler, always_copy: bool) -> Self {
        Self { fs_handler, always_copy }
    }

    pub fn apply(&self, action: Action) -> TFMTResult<Vec<Action>> {
        let actions = match action {
            Action::MoveFile(rename_action) => {
                if self.always_copy {
                    self.fs_handler.copy_file(
                        rename_action.source(),
                        rename_action.target(),
                    )?;

                    let source = rename_action.source().to_owned();

                    vec![
                        Action::CopyFile(rename_action),
                        Action::RemoveFile(source),
                    ]
                } else {
                    let result = self.fs_handler.move_file(
                        rename_action.source(),
                        rename_action.target(),
                    )?;

                    if let MoveFileResult::CopiedAndRemoved = result {
                        let source = rename_action.source().to_owned();

                        vec![
                            Action::CopyFile(rename_action),
                            Action::RemoveFile(source),
                        ]
                    } else {
                        vec![Action::MoveFile(rename_action)]
                    }
                }
            },
            Action::CopyFile(..) => {
                unreachable!(
                    "Action::CopyFile should be generated by ActionHandler::apply, never provided to it."
                )
            },
            Action::RemoveFile(..) => {
                unreachable!(
                    "Action::RemoveFile should be generated by ActionHandler::apply, never provided to it."
                )
            },
            Action::MakeDir(path) => {
                self.fs_handler.create_dir(&path)?;

                vec![Action::MakeDir(path)]
            },
            Action::RemoveDir(path) => {
                self.fs_handler.remove_dir(&path)?;

                vec![Action::RemoveDir(path)]
            },
        };

        Ok(actions)
    }

    pub fn undo(&self, action: &Action) -> TFMTResult<()> {
        match action {
            Action::MoveFile(rename_action) => {
                self.fs_handler.move_file(
                    rename_action.target(),
                    rename_action.source(),
                )?;
            },
            Action::CopyFile(rename_action) => {
                self.fs_handler.copy_file(
                    rename_action.target(),
                    rename_action.source(),
                )?;

                self.fs_handler.remove_file(rename_action.target())?;
            },
            Action::RemoveFile(_path) => {
                trace!(
                    "Ignoring undo of Action::RemoveFile, handled by associated Action::CopyFile"
                );
            },
            Action::MakeDir(path) => {
                self.fs_handler.remove_dir(path)?;
            },
            Action::RemoveDir(path) => {
                self.fs_handler.create_dir(path)?;
            },
        }

        Ok(())
    }

    pub fn redo(&self, action: &Action) -> TFMTResult<()> {
        match action {
            Action::MoveFile(rename_action) => {
                self.fs_handler.move_file(
                    rename_action.source(),
                    rename_action.target(),
                )?;
            },
            Action::CopyFile(rename_action) => {
                self.fs_handler.copy_file(
                    rename_action.source(),
                    rename_action.target(),
                )?;
            },
            Action::RemoveFile(path) => {
                self.fs_handler.remove_file(path)?;
            },
            Action::MakeDir(path) => {
                self.fs_handler.create_dir(path)?;
            },
            Action::RemoveDir(path) => {
                self.fs_handler.remove_dir(path)?;
            },
        }

        Ok(())
    }
}
