name: CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  linux:
    name: Linux Checks
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Run CI script
        uses: ./.forgejo/actions/rust-run
        with:
          command: scripts/ci.sh
