FROM rust:1.89-bookworm

RUN rustup toolchain install nightly --allow-downgrade --profile minimal \
    --component rustfmt \
    --component clippy

COPY entrypoint.sh /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
